"use strict";
exports.__esModule = true;
exports.WithdrawData = exports.GameContract = exports.DepositData = exports.GameDeposit = exports.Add = void 0;
var Add_js_1 = require("./Add.js");
exports.Add = Add_js_1.Add;
var gamedeposit_js_1 = require("./gamedeposit.js");
exports.GameDeposit = gamedeposit_js_1.GameDeposit;
exports.DepositData = gamedeposit_js_1.DepositData;
var gamecontract_js_1 = require("./gamecontract.js");
exports.GameContract = gamecontract_js_1.GameContract;
exports.WithdrawData = gamecontract_js_1.WithdrawData;
